package view;

import interface_adapter.Collect_Questions.CollectQuestionsState;
import interface_adapter.Collect_Questions.CollectQuestionsViewModel;
import interface_adapter.ViewManagerModel;
import interface_adapter.end_game.EndGameState;
import interface_adapter.end_game.EndGameViewModel;
import interface_adapter.login.LoginViewModel;
import interface_adapter.signup.SignupViewModel;
import use_case.collect_questions.CollectQuestionInteractor;

import javax.swing.*;
import javax.swing.border.Border;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;

public class EndGameView extends JPanel implements ActionListener, PropertyChangeListener {

   public final String viewName = "End game";

   private final EndGameViewModel endGameViewModel;

   //private final EndGameController endGameController;

   private final JButton replay;

   private final JButton exit;


   // Only button with use case linked to this

   //private final JButton leaderboards;
   private Color background = new Color(57,54,70);
   private Color textColor = new Color(244, 238, 224);
   private Border blackLine = BorderFactory.createLineBorder(textColor);
   private final JLabel totalQErrorField = new JLabel();

   private JLabel userOutput;

   private JTextArea userOutputLBMCQ;
   private JTextArea userOutputLBTF;

   private JLabel userScore;

   public EndGameView(EndGameViewModel endGameViewModel, SignupViewModel signupViewModel,
                      CollectQuestionsViewModel collectQuestionsViewModel, ViewManagerModel viewManagerModel){

      this.setLayout(null);
      this.setBackground(background);
      //this.endGameController = controller;
      this.endGameViewModel = endGameViewModel;
      this.endGameViewModel.addPropertyChangeListener(this);

      JLabel title = new JLabel(EndGameViewModel.TITLE);
      title.setFont(new Font("Arial",Font.BOLD,27));
      title.setForeground(textColor);
      title.setAlignmentX(Component.CENTER_ALIGNMENT);

      // This is all to display the result grabbed from Devs useCase
      EndGameState endGameState = new EndGameState();
      String output = endGameState.getOutput();

      //TODO: Add User Score implementation here [Get rid of temp "10" value]
      JLabel userScoreTitle = new JLabel(EndGameViewModel.USER_RESULT_LABEL);
      userScoreTitle.setFont(new Font("Arial",Font.BOLD,24));
      userScoreTitle.setForeground(textColor);

      userScore = new JLabel("10");
      userScore.setForeground(textColor);
      userScore.setBackground(new Color(57, 55, 64));
      userScore.setFont(new Font("Arial",Font.BOLD, 20));
      userScore.setAlignmentX(Component.CENTER_ALIGNMENT);
      userScore.setBorder(blackLine);

      //Replace output with placeholder while updating GUI
      JLabel userOutput = new JLabel(output);
      userOutput.setAlignmentX(Component.LEFT_ALIGNMENT);

      //Extra, This is to display the string output generated by Dev's run of the leaderboard
      String outputLBoard = """
              Player1 - 100,000
              GamerPro - 95,000
              ScoreMaster - 90,000
              GameChamp - 85,000
              ProGamerXYZ - 80,000
              HighScorer123 - 75,000
              EpicPlayer - 70,000
              MegaGamer9000 - 65,000
              TopScoreGuy - 60,000
              GamingLegend - 55,000""";


      String TFLeaderBoard = ""; //TODO: Fill this with the leaderboard

      //Replace outputLBoard with placeholder while updating GUI
      userOutputLBMCQ = new JTextArea(outputLBoard);
      userOutputLBMCQ.setForeground(textColor);
      userOutputLBMCQ.setBackground(new Color(57, 55, 64));
      userOutputLBMCQ.setFont(new Font("Arial",Font.PLAIN, 14));
      userOutputLBMCQ.setAlignmentX(Component.LEFT_ALIGNMENT);
      userOutputLBMCQ.setBorder(blackLine);
      //Set MCQ Label
      JLabel MCQLabel = new JLabel(EndGameViewModel.MCQ_LEADERBOARD_LABEL);
      MCQLabel.setFont(new Font("Arial",Font.BOLD,20));
      MCQLabel.setForeground(textColor);


      userOutputLBTF = new JTextArea(outputLBoard); //TODO: MAKE SURE YOU CHANGE THIS
      userOutputLBTF.setForeground(textColor);
      userOutputLBTF.setBackground(new Color(57, 55, 64));
      userOutputLBTF.setFont(new Font("Arial",Font.PLAIN, 14));
      userOutputLBTF.setAlignmentX(Component.LEFT_ALIGNMENT);
      userOutputLBTF.setBorder(blackLine);

      //Set True/False Label
      JLabel TFLabel = new JLabel(EndGameViewModel.TF_LEADERBOARD_LAVEL);
      TFLabel.setFont(new Font("Arial",Font.BOLD,20));
      TFLabel.setForeground(textColor);


      replay = new JButton(EndGameViewModel.REPLAY_BUTTON_LABEL);
      exit = new JButton(EndGameViewModel.EXIT_BUTTON_LABEL);

      replay.setFont(new Font("Arial",Font.BOLD, 20));
      exit.setFont(new Font("Arial",Font.BOLD, 20));

      replay.addActionListener(                // Starts the game again
              new ActionListener() {
                 public void actionPerformed(ActionEvent evt) {
                    if (evt.getSource().equals(replay)) {

                           viewManagerModel.setActiveView(collectQuestionsViewModel.getViewName());
                           viewManagerModel.firePropertyChanged();

                    }
                 }
              }
      );

      exit.addActionListener(                // Returns to signup
              evt -> {
                 if (evt.getSource().equals(exit)) {

                    viewManagerModel.setActiveView(signupViewModel.getViewName());
                    viewManagerModel.firePropertyChanged();

                 }
              }
      );

      // Set the positions of the panels (Frame is 1024x800)
      title.setBounds(450,0,200,100);
      exit.setBounds(700,400,200,100);
      replay.setBounds(700,200,200,100);
      userOutputLBMCQ.setBounds(55,170,250,200);
      userOutputLBTF.setBounds(345,170,250,200);
      MCQLabel.setBounds(55, 45,500,200);
      TFLabel.setBounds(345, 45,500,200);
      userScoreTitle.setBounds(225,390,200,100);
      userScore.setBounds(225,425,200,95);

      // Adding to Panel
      this.add(title);
      this.add(userOutput);
      this.add(userOutputLBMCQ);
      this.add(exit);
      this.add(replay);
      this.add(MCQLabel);
      this.add(TFLabel);
      this.add(userOutputLBTF);
      this.add(userScoreTitle);
      this.add(userScore);
   }


   @Override
   public void actionPerformed(ActionEvent evt) {
      System.out.println("Click " + evt.getActionCommand());
   }

   @Override
   public void propertyChange(PropertyChangeEvent evt) {
      System.out.println("Issue found, please fix this right away");
   }

}
